apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  USER_SERVICE_URL: http://user-service:8000
  PRODUCT_SERVICE_URL: http://product-service:8000
  CART_SERVICE_URL: http://cart-service:8000
  INVENTORY_SERVICE_URL: http://inventory-service:8000
  ORDER_SERVICE_URL: http://order-service:8000
  PAYMENT_SERVICE_URL: http://payment-service:8000
  ADMIN_SERVICE_URL: http://admin-service:8000

