apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
type: Opaque
stringData:
  SMTP_SMARTHOST: smtp-relay.brevo.com:587
  SMTP_FROM: ab476b001@smtp-brevo.com
  SMTP_USERNAME: ab476b001@smtp-brevo.com
  SMTP_PASSWORD: change-me
  ALERT_EMAIL_TO: chandramahesh93900@gmail.com
